### ISSUE TITLE
Add compiler options as parameters?

### ISSUE THREAD

**Issue by kellertuer** [julia-actions/julia-runtest#56] opened 2022-07-22 09:36 UTC
I would like to be able to run (some of) my tests with `Julia -O0 --compile=min` could this action maybe have those as parameters or a parameter `Julia-cmd-options`?

**Comment by SaschaMann** [comment] 2022-07-22 09:48
Thanks for the issue. It's a duplicate of #47. 

I still stand by [what I said there](https://github.com/julia-actions/julia-runtest/issues/47#issuecomment-876524763) but given that it seems to be a popular request, we should probably add it.

**Closed by SaschaMann** 2022-07-22 09:48 UTC
